# Generated by Django 3.2.3 on 2021-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='audiofile_path',
            field=models.FilePathField(default='audio_files'),
        ),
    ]
