# Generated by Django 3.2.3 on 2021-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_audiofile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='audiofile_path',
            field=models.CharField(max_length=255),
        ),
    ]
