# Generated by Django 3.2.3 on 2021-05-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_call_audiofile_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-id']},
        ),
    ]
